config/routes.rb
Rails.application.routes.draw do
 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'billings/index'
  get 'orders/create'
  get 'search/index'
  get 'welcome/index'
  get 'welcome/paneladmin'
  root 'welcome#index'
  resources :marcas do 
    resources :models 
  end
  
  devise_for :users
  resources :cars do 
    resources :orders, only: :create
  end

  resources :billings, only: :index do 
    collection do
      get 'execute'
    end
  end

  resources :orders, only: :index do
    collection do
      get 'clean'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :car
  belongs_to :user
  scope :cart, -> {where(payed: false)}

  
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def create
    c = Car.find(params[:car_id])
    o = Order.find_or_create_by(user: current_user, car: c, price: c.price, payed: false)

    if o.save
      redirect_to orders_path
    else
      redirect_to cars_path
    end
  end

  def clean
    @orders = Order.where(user: current_user, payed: false)
    @orders.destroy_all
    redirect_to orders_path, notice: 'El carro se ha vaciado.'
  end

  def index
    @orders = Order.cart
    
  end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<h1 class="text-center">Ordenes para pago</h1>
<div class="container">
    <% if @orders.count > 0 %>
    <table class="table table-striped">
    <thead>
        <tr>
        <th scope="col">Marca</th>
        <th scope="col">Modelo</th>
        <th scope="col">Patente</th>
        <th scope="col">Dueño</th>
        <th scope="col">Precio</th>
        <th></th>
        </tr>
    </thead>
    <tbody>
    <% @orders.each do |order| %>
        <tr>
        <td> <%= order.car.marca %> </td>
        <td> <%= order.car.model %></td>
        <td> <%= order.car.ppu %> </td>
        <td> <%= order.car.client %></td>
        <td><p>$<%= order.car.price %></p></td>
        <td><%= link_to "Pagar", execute_billings_path, class:'btn btn-outline-warning' %></td>
        <td><%= link_to "Borrar", clean_orders_path, class:'btn btn-danger' %></td>
        </tr>
        <% end %>
        
    </tbody>
    </table>
    <% else %>
        <p>No hay ordenes para cobrar</p>
    <%end%>
    <%= link_to "Back", cars_path, class:'btn btn-outline-primary' %>
</div>