config/routes.rb
Rails.application.routes.draw do
 
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'billings/index'
  get 'orders/create'
  get 'search/index'
  get 'welcome/index'
  get 'welcome/paneladmin'
  root 'welcome#index'
  resources :marcas do 
    resources :models 
  end
  
  devise_for :users
  resources :cars do 
    resources :orders, only: :create
  end

  resources :billings, only: :index do 
    collection do
      get 'execute'
    end
  end

  resources :orders, only: :index do
    collection do
      get 'clean'
    end
  end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/car.rb
class Car < ApplicationRecord
    has_many :marcas
    has_many :models
    has_many :orders
    has_many :users, through: :orders

    def self.created_by_day
        group_by_day(:created_at).count

    end
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_car, only: [:show, :edit, :update, :destroy]

  # GET /cars
  # GET /cars.json
  def index
    @cars = Car.all
  
  end

  # GET /cars/1
  # GET /cars/1.json
  def show
  end

  # GET /cars/new
  def new
    @car = Car.new
  end

  # GET /cars/1/edit
  def edit
  end

  # POST /cars
  # POST /cars.json
  def create
    @car = Car.new(car_params)

    respond_to do |format|
      if @car.save
        format.html { redirect_to @car, notice: 'Car was successfully created.' }
        format.json { render :show, status: :created, location: @car }
      else
        format.html { render :new }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cars/1
  # PATCH/PUT /cars/1.json
  def update
    respond_to do |format|
      if @car.update(car_params)
        format.html { redirect_to @car, notice: 'Car was successfully updated.' }
        format.json { render :show, status: :ok, location: @car }
      else
        format.html { render :edit }
        format.json { render json: @car.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cars/1
  # DELETE /cars/1.json
  def destroy
    @car.destroy
    respond_to do |format|
      format.html { redirect_to cars_url, notice: 'Car was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_car
      @car = Car.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def car_params
      params.require(:car).permit(:client, :marca, :model, :year, :ppu, :mec, :diagnostico, :price)
    end
end

app/helpers/cars_helper.rb
module CarsHelper
end

app/views/cars/_form.html.erb
<div class="col-md-8 mt-4">
  <div class="card">
    <div class="card-body">
      <%= form_with(model: car, local: true) do |form| %>
        <% if car.errors.any? %>
          <div id="error_explanation">
            <h2><%= pluralize(car.errors.count, "error") %> prohibited this car from being saved:</h2>

            <ul>
            <% car.errors.full_messages.each do |message| %>
              <li><%= message %></li>
            <% end %>
            </ul>
          </div>
        <% end %>

        <div class="form-group">
          <%= form.label :Cliente %>
          <%= form.text_field :client, class:'form-control', placeholder: 'Escriba Nombre y Apellido' %>
        </div>

        <div class="form-group">
          <%= form.label :marca %>
          <%= form.text_field :marca, class:'form-control', placeholder: 'Marca del vehiculo' %>
        </div>

        <div class="form-group">
          <%= form.label :modelo %>
          <%= form.text_field :model, class:'form-control', placeholder: 'Modelo del vehiculo' %>
        </div>

        <div class="form-group">
          <%= form.label :Año %>
          <%= form.number_field :year, class:'form-control' %>
        </div>

        <div class="form-group">
          <%= form.label :Patente %>
          <%= form.text_field :ppu, class:'form-control', placeholder: 'Patente del vehiculo' %>
        </div>

        <div class="form-group">
          <%= form.label :Mecanico %>
          <%= form.text_field :mec, class:'form-control', placeholder: 'Mecanico encargado' %>
        </div>

        <div class="form-group">
          <%= form.label :Motivo %>
          <%= form.text_area :diagnostico, class:'form-control', placeholder: 'Escriba el motivo por que ingresa' %>
        </div>

        <div class="form-group">
          <%= form.label :Precio %>
          <%= form.number_field :price, class:'form-control' %>
        </div>
        <br>      
        <div class="btn btn-success">
          <%= form.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/cars/edit.html.erb
<h1>Editing Car</h1>

<%= render 'form', car: @car %>

<%= link_to 'Show', @car %> |
<%= link_to 'Back', cars_path %>

app/views/cars/index.html.erb
<p id="notice"><%= notice %></p>

<h1 class="text-center">Autos</h1>
<div class="container">
  <div class="table-responsive">
    <table class="table">
      <thead class="thead-dark">
        <tr>
          <th>Cliente</th>
          <th>Marca</th>
          <th>Model</th>
          <th>Year</th>
          <th>Ppu</th>
          <th>Mecanico</th>
          <th>Diagnostico</th>
          <th>Precio</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
      
        <% @cars.each do |car| %>
          <tr>
            <td><%= car.client %></td>
            <td><%= car.marca %></td>
            <td><%= car.model %></td>
            <td><%= car.year %></td>
            <td><%= car.ppu %></td>
            <td><%= car.mec %></td>
            <td><%= car.diagnostico %></td>
            <td><p>$<%= car.price %></p></td>
            <td><%= link_to 'Listo', car_orders_path(car), class:'btn btn-outline-info', method: :post %></td>
            <td><%= link_to 'Edit', edit_car_path(car), class:'btn btn-success' %></td>
            <% if can? :destroy, car%>
            <td><%= link_to 'Destroy', car, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-warning' %></td>
            <% end %>
            </tr>
        <% end %>
      </tbody>
    </table>
  </div>
  <% if can? :new, @cars %>
    <%= link_to 'New Car', new_car_path, class:'btn btn-outline-danger' %>
  <% end %>
  <% if can? :read, Order %>
    <%= link_to 'Ordenes', orders_path, class:'btn btn-outline-success float-right' %>
  <% end %>
</div>
<br>

app/views/cars/new.html.erb
<h1>Ingreso de Nuevo Auto</h1>

<%= render 'form', car: @car %>
<br>
<%= link_to 'Back', cars_path %>

app/views/cars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Marca:</strong>
  <%= @car.marca %>
</p>

<p>
  <strong>Model:</strong>
  <%= @car.model %>
</p>

<p>
  <strong>Year:</strong>
  <%= @car.year %>
</p>

<p>
  <strong>Patente:</strong>
  <%= @car.ppu %>
</p>

<p>
  <strong>Diagnostico:</strong>
  <%= @car.diagnostico %>
</p>

<%= link_to 'Edit', edit_car_path(@car) %> |
<%= link_to 'Back', cars_path %>